from typing import Final

FREE_SPACE: Final = "FREE SPACE"

# Personality Bingo - Focus on personality traits and characteristics
PERSONALITY_BINGO: Final[list[str]] = [
    "is an introvert",
    "is a morning person",
    "is a night owl",
    "loves public speaking",
    "is naturally artistic",
    "has a dry sense of humor",
    "is a perfectionist",
    "is spontaneous",
    "is competitive",
    "is very organized",
    "is a good listener",
    "is adventurous",
    "is patient with others",
    "is an extrovert",
    "takes things personally",
    "is easygoing",
    "is ambitious",
    "is naturally curious",
    "overthinks decisions",
    "is confident in their abilities",
    "is diplomatic",
    "has a contagious laugh",
    "is a natural leader",
    "is empathetic",
]

# Lifestyle Bingo - Focus on daily habits and lifestyle choices
LIFESTYLE_BINGO: Final[list[str]] = [
    "bikes to work",
    "has a pet",
    "prefers tea over coffee",
    "plays an instrument",
    "does yoga",
    "has a garden",
    "plays video games",
    "loves cooking",
    "is a bookworm",
    "works from home",
    "exercises regularly",
    "is vegetarian or vegan",
    "meditates",
    "loves hiking",
    "is a morning runner",
    "loves spicy food",
    "does volunteer work",
    "collects something unique",
    "has a daily journal",
    "is a coffee enthusiast",
    "loves board games",
    "practices photography",
    "has a side hustle",
    "is a fitness enthusiast",
]

# Travel Bingo - Focus on travel experiences and adventures
TRAVEL_BINGO: Final[list[str]] = [
    "has lived in another country",
    "was born in a different state",
    "has traveled to Asia",
    "has been skydiving",
    "has met a celebrity",
    "has been on TV",
    "speaks more than 2 languages",
    "has run a marathon",
    "has a passport stamp from 5+ countries",
    "has been to Europe",
    "has visited Disney World",
    "has been on a cruise",
    "has hiked a famous mountain",
    "has traveled solo",
    "has been to South America",
    "has attended a major festival",
    "has been to Australia",
    "has ridden an exotic animal",
    "has visited all US states",
    "has been to Africa",
    "has worked abroad",
    "has taken a road trip across the US",
    "has visited a famous landmark",
    "has done a dangerous activity abroad",
]

# Tech Life Bingo - Focus on coding habits, IDE preferences, and developer culture
TECH_LIFE_BINGO: Final[list[str]] = [
    "uses dark mode for everything",
    "has 50+ browser tabs open right now",
    "knows vim keybindings",
    "has a mechanical keyboard",
    "prefers tabs over spaces",
    "has strong opinions about semicolons",
    "uses AI to write commit messages",
    "has a dotfiles repository",
    "has contributed to open source",
    "uses VS Code",
    "uses IntelliJ / JetBrains IDE",
    "has deployed to production on Friday",
    "codes with music or podcasts",
    "debugs with console.log",
    "attends tech conferences",
    "uses Linux as daily driver",
    "has shipped code they're proud of",
    "participates in hackathons",
    "uses GitHub",
    "has written a technical blog post",
    "codes late at night",
    "has fixed a bug in production",
    "prefers pair programming",
    "has crushed a technical interview",
]

# Default to Personality Bingo - can be overridden by game session
QUESTIONS: Final[list[str]] = PERSONALITY_BINGO
